routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){

    Route::get('/home', [

        'uses' => "ContainersController@index",
        'as' => "home"
        
    ]);
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::Resource('containers', 'ContainersController');
    Route::post("clone_fields", ['as' => 'clone_fields', 'uses' => 'ContainersController@getClonedFields']);
    
});

app/Container.php
<?php

namespace App;

use Auth;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Container extends Model
{
    //

    use SoftDeletes;

    protected $fillable = [
        'bl_no',
        'container_no',
        'size',
        'owner',
        'status',
        'eta',
        'date_received',
        'line',
        'items',
        'pay_balance',
        'delivery_status',

    ];

    public $incrementing = false;
    protected $keyType = 'string';
    protected $primaryKey = 'container_no';
    protected $dates = ['deleted_at'];

    public static function boot()
    {
        parent::boot();
        static::creating(function($container)
        {
            $container->created_by = Auth::user()->id;
            $container->updated_by = Auth::user()->id;
        });
        

        static::updating(function($container)
        {
            $container->updated_by = Auth::user()->id;
        });
    }

    public function expenses()
    {
        return $this->hasMany('App\Expense', 'container_id', 'container_no');
    }
}

app/Http/Controllers/ContainersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Container;
use App\Expense;
use App\Item;
use Auth;
use Illuminate\Support\Facades\Input;

class ContainersController extends Controller
{

    function __construct()
    {
         $this->middleware('permission:container-list|container-create|container-edit|container-delete', ['only' => ['index','show']]);
         $this->middleware('permission:container-create', ['only' => ['create','store']]);
         $this->middleware('permission:container-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:container-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('admin.containers.index')->with('containers', Container::all());

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.containers.create');
       
    }

    public function getClonedFields() {
        $input = Input::all();
        $id = $input['div_count'];
        $varId = 'removeId'. $id;
        $data = '
                <div class="clonedInput form-group row" id="'.$varId.'">
                <div class="col-md-3 col-lg-3">
                    <select required="required" id="item_name'. $varId .'" class="form-control" name="item_name[]">
                        @foreach ($expense_items as $key => $val)
                        <option value="{{ $key }}">{{ $val }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-md-3 col-lg-3">
                    <input id="item_name'. $varId .'" type="text" class="form-contro name="item_expenditure[]" required autocomplete="item_expenditure">
                </div>
                <div class="col-md-3 col-lg-3">
                    <input id="item_date'. $varId .'" type="date" class="form-control  name="item_date[]" required autocomplete="item_date[]">
                </div>
                <div class="col-md-3 col-lg-3">
                    <input id="item_pay_status'. $varId .'" type="text" class="form-control name="item_pay_status[]" required autocomplete="item_pay_status">
                </div>
                <div class="col-md-1">
                  <input type="button" class="btn btn-danger" name="del_item" value="Delete" onClick="removedClone('. $varId .');" />
                </div>
            </div>
        ';
        echo json_encode($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validatedData = $request->validate([
            'bl_no' => 'required',
            'container_no' => 'required',
            'size' => 'required',
            'owner' => 'required',
            'status' => 'required',
            'eta' => 'required',
            'date_received' => 'required',
            'line' => 'required',
            'items' => 'required',
            'pay_balance' => '',
            'delivery_status' => 'required',
        ]);

       
        $container = Container::create([
            'bl_no' => $validatedData['bl_no'],
            'container_no' => $validatedData['container_no'],
            'size' => $validatedData['size'],
            'owner' => $validatedData['owner'],
            'status' => $validatedData['status'],
            'eta' => $validatedData['eta'],
            'date_received' => $validatedData['date_received'],
            'line' => $validatedData['line'],
            'pay_balance' => $validatedData['pay_balance'],
            'delivery_status' => $validatedData['delivery_status'],
            'items' => $validatedData['items'],
        ]);

        $expense = new Expense;
        $expense->container_id = $container->container_no;
        $expense->save();
        $container->expense_id = $expense->id;
        $container->save();

        return redirect('/admin/containers')->with('success', 'container added successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //

        $containers = Container::find($id);
        $expenses =  Container::find($id)->expenses;
        $expense_items = ['PAAR', 'SHIPPING', 'APM TERMINALS APP', 'CAPTURING', 'SGD', 'DUTY', 'ICNL KD', 'DC CUSTOMS', 'TRANSPORT', 'SON', 'GT,RLS,LBR,LCK,AGNCY', 'STRIKE FORCE', 'AGENCY', 'OTHERS' ];

        return view('admin.containers.edit', compact(['containers', 'expenses', 'expense_items']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //

        $validatedData = $request->validate([
            'bl_no' => 'required',
            'container_no' => 'required',
            'size' => 'required',
            'owner' => 'required',
            'status' => 'required',
            'eta' => 'required',
            'date_received' => 'required',
            'line' => 'required',
            'items' => 'required',
            'payment_balance' => '',
            'delivery_status' => 'required',
            'item'
        ]);

        $container = Container::find($id);
        $container->bl_no = $validatedData['bl_no'];
        $container->container_no = $validatedData['container_no'];
        $container->size = $validatedData['size'];
        $container->owner = $validatedData['owner'];
        $container->status = $validatedData['status'];
        $container->eta = $validatedData['eta'];
        $container->date_received = $validatedData['date_received'];
        $container->line = $validatedData['line'];
        $container->pay_balance = $validatedData['payment_balance'];
        $container->delivery_status = $validatedData['delivery_status'];
        $container->items = $validatedData['items'];
        $container->save();

        for($i=0; $i<count($request['item_name']); $i++) {
            $data['item_name'] = $request['item_name'][$i];
            $data['item_expenditure'] = $request['item_expenditure'][$i];
            $data['item_date'] = $request['item_date'][$i];
            $data['item_pay_status'] = $request['item_pay_status'][$i];
            $expense = new Expense;
            $expense->container_id = $container->container_no;
            $expense->item =  $data['item_name'];
            $expense->expenditure = $data['item_expenditure'];
            $expense->date =  $data['item_date'];
            $expense->payment_status =  $data['item_pay_status'];
            $expense->save();
        }

        return redirect('/admin/containers')->with('success', 'container Updated successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $container = Container::findOrFail($id);
        $container->delete();

        return redirect('/admin/containers')->with('success', 'container deleted successfully');
    }
}

resources/views/admin/containers/create.blade.php
@extends('layouts.app');

@section('content')

<div class="card">
    <div class="card-header">Add a New Container</div>

    <div class="card-body">
        <form method="POST" action="{{ route('containers.store') }}">
                @csrf
            <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-right">BL No.</label>
                <div class="col-md-6">
                    <input id="bl_no" type="text" class="form-control" name="bl_no" value="{{ old('bl_no') }}" required>

                    @error('bl_no')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>

            <div class="form-group row">
                <label for="email" class="col-md-4 col-form-label text-md-right">Container No.</label>

                <div class="col-md-6">
                    <input id="container_no" type="text" class="form-control @error('container_no') is-invalid @enderror" name="container_no" value="{{ old('container_no') }}" required autocomplete="container_no">

                    @error('container_no')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>

            <div class="form-group row">
                <label for="size" class="col-md-4 col-form-label text-md-right">Size</label>

                <div class="col-md-6">
                    <input id="size" type="text" class="form-control @error('size') is-invalid @enderror" name="size" required autocomplete="size">

                    @error('size')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>

            <div class="form-group row">
                <label for="owner" class="col-md-4 col-form-label text-md-right">Owner</label>

                <div class="col-md-6">
                    <input id="owner" type="text" class="form-control" name="owner" required autocomplete="owner">

                    @error('owner')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>

            <div class="form-group row">
                <label for="line" class="col-md-4 col-form-label text-md-right">Line</label>

                <div class="col-md-6">
                    <input id="line" type="text" class="form-control" name="line" required autocomplete="line">

                    @error('line')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>

            <div class="form-group row">
                <label for="items" class="col-md-4 col-form-label text-md-right">Item (s)</label>

                <div class="col-md-6">
                    <input id="items" type="text" class="form-control" name="items" required autocomplete="items">

                    @error('items')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>

            <div class="form-group row">
                <label for="status" class="col-md-4 col-form-label text-md-right">Status</label>

                <div class="col-md-6">
                    <input id="status" type="text" class="form-control @error('status') is-invalid @enderror" name="status" required autocomplete="status">

                    @error('status')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>

            <div class="form-group row">
                <label for="eta" class="col-md-4 col-form-label text-md-right">ETA</label>

                <div class="col-md-6">
                    <input id="eta" type="text" class="form-control" name="eta" required autocomplete="eta">

                    @error('eta')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>

            <div class="form-group row">
                <label for="date_received" class="col-md-4 col-form-label text-md-right">Date Received</label>

                <div class="col-md-6">
                    <input id="date_received" type="date" class="form-control @error('date_received') is-invalid @enderror" name="date_received" required autocomplete="date_received">

                    @error('date_received')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>

            <div class="form-group row">
                <label for="pay_balance" class="col-md-4 col-form-label text-md-right">Pay Balance</label>

                <div class="col-md-6">
                    <input id="pay_balance" type="text" class="form-control @error('pay_balance') is-invalid @enderror" name="pay_balance"  autocomplete="pay_balance">

                    @error('pay_balance')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>

            <div class="form-group row">
                <label for="delivery_status" class="col-md-4 col-form-label text-md-right">Delivery Status</label>

                <div class="col-md-6">
                    <input id="delivery_status" type="text" class="form-control" name="delivery_status" required autocomplete="delivery_status">

                    @error('delivery_status')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>

            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        Add Container
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@stop

resources/views/admin/containers/edit.blade.php
@extends('layouts.app');

@section('content')

<div class="card">
    <div class="card-header card-primary">Edit Container [{{ $containers->container_no }}]</div>
    <div class="card-body">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            <br /> 
        @endif
        <form method="POST" action="{{ route('containers.update', $containers->container_no) }}">
                @method('PATCH') 
                @csrf
                <div class="row">
                    <div class="col-md-6 col-lg-6">
                        <div class="form-group row">
                            <label for="name" class="col-md-3 col-lg-3 col-form-label text-md-right">BL No.</label>
                            <div class="col-md-6">
                                <input id="bl_no" type="text" class="form-control" name="bl_no" value="{{ $containers->bl_no }}" readonly required>

                                @error('bl_no')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-3 col-lg-3 col-form-label text-md-right">Container No.</label>

                            <div class="col-md-6">
                                <input id="container_no" type="text" class="form-control @error('container_no') is-invalid @enderror" readonly name="container_no" value="{{ $containers->container_no}}" required autocomplete="container_no">

                                @error('container_no')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="size" class="col-md-3 col-lg-3 col-form-label text-md-right">Size</label>

                            <div class="col-md-6">
                                <input id="size" type="text" class="form-control @error('size') is-invalid @enderror" name="size" value="{{ $containers->size }}" required autocomplete="size">

                                @error('size')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="owner" class="col-md-3 col-lg-3 col-form-label text-md-right">Owner</label>

                            <div class="col-md-6">
                                <input id="owner" type="text" class="form-control" name="owner" value="{{ $containers->owner }}" required autocomplete="owner">

                                @error('owner')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="line" class="col-md-3 col-lg-3 col-form-label text-md-right">Line</label>

                            <div class="col-md-6">
                                <input id="line" type="text" class="form-control" name="line" value="{{ $containers->line }}" required autocomplete="line">

                                @error('line')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="line" class="col-md-3 col-lg-3 col-form-label text-md-right">Item (s)</label>

                            <div class="col-md-6">
                                <input id="items" type="text" class="form-control" name="items" value="{{ $containers->items }}" required autocomplete="items">

                                @error('items')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                    </div>
                    <div class="col-md-6 col-lg-6">
                        <div class="form-group row">
                            <label for="status" class="col-md-3 col-lg-3 col-form-label text-md-right">Status</label>

                            <div class="col-md-6">
                                <input id="status" type="text" class="form-control @error('status') is-invalid @enderror" name="status" value="{{ $containers->status }}" required autocomplete="status">

                                @error('status')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="eta" class="col-md-3 col-lg-3 col-form-label text-md-right">ETA</label>

                            <div class="col-md-6">
                                <input id="eta" type="text" class="form-control" name="eta" value="{{ $containers->eta }}" required autocomplete="eta">

                                @error('eta')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="date_received" class="col-md-3 col-lg-3 col-form-label text-md-right">Date Received</label>

                            <div class="col-md-6">
                                <input id="date_received" type="date" class="form-control @error('date_received') is-invalid @enderror" name="date_received" value="{{ $containers->date_received }}" required autocomplete="date_received">

                                @error('date_received')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="delivery_status" class="col-md-3 col-lg-3 col-form-label text-md-right">Delivery Status</label>

                            <div class="col-md-6">
                                <input id="delivery_status" type="text" class="form-control" name="delivery_status" value="{{ $containers->delivery_status }}" required autocomplete="delivery_status">

                                @error('delivery_status')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="payment_balance" class="col-md-3 col-lg-3 col-form-label text-md-right">Payment Balance</label>

                            <div class="col-md-6">
                                <input id="payment_balance" type="text" class="form-control" name="payment_balance" value="{{ $containers->pay_balance }}" autocomplete="payment_balance">

                                @error('payment_balance')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        </div>
                </div>
                <hr>
                <button type="button" class="btn btn-success btn-add-expense"><i class="fa fa-plus"></i> Add Expense</button>
                    <br><br>
                <div class="form-group row">
                    <div class="col-md-3 col-lg-3">
                        Item
                    </div>
                    <div class="col-md-3 col-lg-3">
                        Expenditure
                    </div>
                    <div class="col-md-3 col-lg-3">
                        Date
                    </div>
                    <div class="col-md-3 col-lg-3">
                        Payment Status
                    </div>
                </div>
                <div class="clonedInput form-group row" id="removeId1">
                    <div class="col-md-3 col-lg-3">
                         <select required="required" class="form-control" name="item_name[]">
                            @foreach ($expense_items as $val)
                            <option value="{{ $val }}">{{ $val }}</option>
                            @endforeach
                         </select>
                    </div>
                    <div class="col-md-3 col-lg-3">
                        <input id="item_expenditure" type="text" class="form-control @error('item_expenditure') is-invalid @enderror" name="item_expenditure[]" required autocomplete="item_expenditure">
                        @error('item_expenditure')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="col-md-3 col-lg-3">
                        <input id="item_date" type="date" class="form-control @error('item_date') is-invalid @enderror" name="item_date[]" required autocomplete="item_date[]">
                        @error('item_date')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="col-md-3 col-lg-3">
                        <input id="item_pay_status" type="text" class="form-control @error('item_pay_status') is-invalid @enderror" name="item_pay_status[]" required autocomplete="item_pay_status">
                        @error('item_pay_status')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4 text-center">
                    <button type="submit" class="btn btn-success">
                        Update
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@stop